
// This is a placeholder service for transcription and summarization
// In a real implementation, this would connect to a speech-to-text API

export interface TranscriptionResult {
  transcription: string;
  summary: string;
}

// Simulated processing time in ms
const PROCESSING_DELAY = 3000;

export const transcribeAndSummarize = async (mediaFile: File): Promise<TranscriptionResult> => {
  // This is a mock function that simulates processing time
  // In a real app, you would send the file to a backend service
  
  return new Promise((resolve) => {
    console.log(`Processing file: ${mediaFile.name} (${mediaFile.type})`);
    
    setTimeout(() => {
      // Simulate different results based on file name to make it more interactive
      const isAudio = mediaFile.type.startsWith('audio/');
      const fileNameLower = mediaFile.name.toLowerCase();
      
      let transcription = "This is a simulated transcription of your media file. In a real application, this text would be generated by processing your audio or video through a speech recognition service. The transcription would capture all spoken words and convert them into text format.";
      let summary = "This is a simulated summary of the media content. In a real application, this would be an AI-generated summary of the key points from the transcription.";
      
      if (fileNameLower.includes('meeting')) {
        transcription = "Person A: Hi everyone, thanks for joining today's meeting.\n\nPerson B: Glad to be here. Let's discuss the project timeline.\n\nPerson A: Sure. We're looking at a six-week development cycle with two weeks for testing.\n\nPerson B: That seems tight. Can we extend the testing period?\n\nPerson A: We could move some resources from documentation to testing.\n\nPerson B: That works for me. Let's proceed with that plan.";
        summary = "Meeting discussion about project timeline. Initially proposed: 6-week development, 2-week testing. Decision made to reallocate resources from documentation to extend the testing period.";
      } else if (fileNameLower.includes('lecture')) {
        transcription = "Today we'll be covering the fundamentals of machine learning. Machine learning is a subset of artificial intelligence where systems can learn from data, identify patterns, and make decisions with minimal human intervention. The main types of machine learning include supervised learning, unsupervised learning, and reinforcement learning. In supervised learning, algorithms are trained on labeled data...";
        summary = "Introduction to machine learning fundamentals, covering definitions and the main types: supervised learning, unsupervised learning, and reinforcement learning. The lecture explains how systems learn from data to identify patterns and make decisions.";
      }
      
      if (isAudio) {
        transcription = `[Audio Transcription] ${transcription}`;
      } else {
        transcription = `[Video Transcription] ${transcription}`;
      }
      
      resolve({
        transcription,
        summary
      });
    }, PROCESSING_DELAY);
  });
};
